namespace MovieReservationSystem.Application.DTOs
{
    public class PaymentRequestDTO
    {
        public string StripeToken { get; set; } // generated by external payment provider
        public string UserId { get; set; }
    }
}
